require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'infinite' do
  config = use_native_modules!
  
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 6.13.0'
  # pod 'Firebase/Crashlytics'
 
  pod 'Firebase/Auth'

  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  pod 'Fabric' 
  pod 'Crashlytics' 
  pod 'Firebase/Analytics'
  pod 'Stripe', '~> 14.0.0' 
  use_react_native!(:path => config["reactNativePath"])
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'RNFirebase/Crashlytics', :path => '../node_modules/react-native-firebase/ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'infiniteTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end
