const bannerKeys = {
  GET_DB_BANNER: 'GET_DB_BANNER',
  SAVE_DB_BANNER: 'SAVE_DB_BANNER',
  GET_WORKOUT_BANNER: 'GET_WORKOUT_BANNER',
  SAVE_WORKOUT_BANNER: 'SAVE_WORKOUT_BANNER',
  SAVE_BLOGS_BANNER: 'SAVE_BLOGS_BANNER',
  SAVE_STORIES_BANNER: 'SAVE_STORIES_BANNER',
}

export default bannerKeys;