const blogsKeys = {
  GET_BLOGS: 'GET_BLOGS',
  SAVE_BLOGS: 'SAVE_BLOGS',
  GET_FEATURED_BLOGS: 'GET_FEATURED_BLOGS',
  SAVE_FEATURED_BLOGS: 'SAVE_FEATURED_BLOGS',
  GET_TREND_BLOGS: 'GET_TREND_BLOGS',
  SAVE_TRENDING_BLOGS: 'SAVE_TRENDING_BLOGS',
  SAVE_CAT_BLOGS: 'SAVE_CAT_BLOGS',
  SAVE_SIMILAR_BLOGS: 'SAVE_SIMILAR_BLOGS',
  GET_BLOG_DETAILS: 'GET_BLOG_DETAILS',
  SAVE_BLOG_DETAILS: 'SAVE_BLOG_DETAILS',
  GET_SIMILAR_BLOG_DETAILS: 'GET_SIMILAR_BLOG_DETAILS',
  SAVE_SIMILAR_BLOG_DETAILS: 'SAVE_SIMILAR_BLOG_DETAILS',
  ADD_BLOG_LIKE: 'ADD_BLOG_LIKE',
  SAVE_BLOG_LIKE: 'SAVE_BLOG_LIKE',
  GET_BLOG_LIKE: 'GET_BLOG_LIKE',
}

export default blogsKeys;