export const guidesKeys = {
  GET_GUIDES_LIST: 'GET_GUIDES_LIST',
  SAVE_GUIDES_LIST: 'SAVE_GUIDES_LIST',
  GET_GUIDE_BANNER: 'GET_GUIDE_BANNER',
  SAVE_GUIDE_BANNER: 'SAVE_GUIDE_BANNER',
  GET_SIMILAR_GUIDE: 'GET_SIMILAR_GUIDE',
  SAVE_SIMILAR_GUIDE: 'SAVE_SIMILAR_GUIDE',
  GET_GUIDE_DTLS: 'GET_GUIDE_DTLS',
  SAVE_GUIDE_DTLS: 'SAVE_GUIDE_DTLS',
  SAVE_SIMILAR_GUIDE_DTLS: 'SAVE_SIMILAR_GUIDE_DTLS',
};
