
const loginKeys = {
  SAVE_TOKEN: 'SAVE_TOKEN',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SAVE_MEAL_ID: 'SAVE_MEAL_ID',
  SOCIAL_LOGIN: 'SOCIAL_LOGIN',
  SIGNUP: 'SIGNUP',
  ERROR: 'ERROR',
  SEND_OTP: 'SEND_OTP',
  VERIFY_OTP: 'VERIFY_OTP',
  GET_USER_INFO: 'GET_USER_INFO',
  SAVE_USER_INFO: 'SAVE_USER_INFO',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  SAVE_USER_RESP: 'SAVE_USER_RESP',
  UPDATE_SIGNUP_STATUS: 'UPDATE_SIGNUP_STATUS',
  UPDATE_STEPS: 'UPDATE_STEPS',
}

export default loginKeys;