const passwordKeys = {
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PWD_RESP: 'FORGOT_PWD_RESP',
  VERIFY_FORGOT_OTP: 'VERIFY_FORGOT_OTP',
  VERIFY_FORGOT_OTP_RESP: 'VERIFY_FORGOT_OTP_RESP',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  STATUS_CHANGE_PWD: 'STTSTATUS_CHANGE_PWDUS_CHANGE_PWD',
}

export default passwordKeys;