const paymentKeys = {
  GET_CARDS: 'GET_CARDS',
  SAVE_CARD_RESP: 'SAVE_CARD_RESP',
  ADD_CARD: 'ADD_CARD',
  ADD_CARD_RESP: 'ADD_CARD_RESP',
  REMOVE_CARD: 'REMOVE_CARD',
  REMOVE_CARD_RESP: 'REMOVE_CARD_RESP',
  PURCHASE_PLAN: 'PURCHASE_PLAN',
  PURCHASE_PLAN_RESP: 'PURCHASE_PLAN_RESP',
}

export default paymentKeys;