const ReliefKeys={
    GET_HOMEREMEDIES: 'GET_HOMEREMEDIES',
    SAVE_HOMEREMEDIES: 'SAVE_HOMEREMEDIES',
    SAVE_HOMEREMEDIES_SRCH: 'SAVE_HOMEREMEDIES_SRCH',

    GET_RELIEFEXERCISE:'GET_RELIEFEXERCISE',
    SAVE_RELIEFEXERCISE: 'SAVE_RELIEFEXERCISE',
    SAVE_RELIEFEXERCISE_SRCH: 'SAVE_RELIEFEXERCISE_SRCH',

    GET_HOMEREMEDIES_DTLS: 'GET_HOMEREMEDIES_DTLS',
    SAVE_HOMEREMEDIES_DTLS: 'SAVE_HOMEREMEDIES_DTLS',

    GET_RELIEFEXERCISE_DTLS:'GET_RELIEFEXERCISE_DTLS',
    SAVE_RELIEFEXERCISE_DTLS: 'SAVE_RELIEFEXERCISE_DTLS',



}


export default ReliefKeys;