const reminderKeys = {
  SAVE_REMINDER: 'SAVE_REMINDER',
  SET_REMINDER_STATUS: 'SET_REMINDER_STATUS',
  GET_REMINDERS: 'GET_REMINDERS',
  SAVE_REMINDERS: 'SAVE_REMINDERS',
  GET_USER_REMINDER: 'GET_USER_REMINDER',
  SAVE_USER_REMINDER: 'SAVE_USER_REMINDER',
  GET_USER_NOTIFICATION: 'GET_USER_NOTIFICATION',
  SAVE_USER_NOTIFICATION: 'SAVE_USER_NOTIFICATIO',
}

export default reminderKeys;