const storiesKeys = {
  GET_STORIES: 'GET_STORIES',
  SAVE_STORIES: 'SAVE_STORIES',
  GET_SIMILAR_STORIES: 'GET_SIMILAR_STORIES',
  SAVE_SIMILAR_STORIES: 'SAVE_SIMILAR_STORIES',
  GET_BANNER_STORIES: 'GET_BANNER_STORIES',
  SAVE_BANNER_STORIES: 'SAVE_BANNER_STORIES',
  GET_STORIES_DETAILS: 'GET_STORIES_DETAILS',
  SAVE_STORIES_DETAILS: 'SAVE_STORIES_DETAILS',
  GET_SIMILAR_STORIES_DETAILS: 'GET_SIMILAR_STORIES_DETAILS',
  SAVE_SIMILAR_STORIES_DETAILS: 'SAVE_SIMILAR_STORIES_DETAILS',
}

export default storiesKeys;