const workoutKeys = {
  GET_EXERCISES_CAT: 'GET_EXERCISES_CAT',
  SAVE_EXERCISES_CAT: 'SAVE_EXERCISES_CAT',
  SAVE_EXERCISES_CAT_SRCH: 'SAVE_EXERCISES_CAT_SRCH',
  GET_EXERCISES_CAT_DTLS: 'GET_EXERCISES_CAT_DTLS',
  SAVE_EXERCISES_CAT_DTLS: 'SAVE_EXERCISES_CAT_DTLS',
  GET_WORKOUTS: 'GET_EXERCISES',
  SAVE_WORKOUTS: 'SAVE_EXERCISES',
  SAVE_WORKOUTS_SRCH: 'SAVE_EXERCISES_SEARCH',
  SAVE_REC_WORKOUT_PLAN: 'SAVE_REC_WORKOUT_PLAN',
  SAVE_REC_PLANS_DTLS: 'SAVE_REC_PLANS_DTLS',
  GET_CAT_WORKOUTS_DTLS: 'GET_CAT_WORKOUTS_DTLS',
  SAVE_CAT_WORKOUTS_DTLS: 'SAVE_CAT_WORKOUTS_DTLS',
  GET_USER_PLAN_DATA: 'GET_USER_PLAN_DATA',
  SAVE_USER_PLAN_DATA: 'SAVE_USER_PLAN_DATA',
  SAVE_WORKOUT_PROGRESS: 'SAVE_WORKOUT_PROGRESS',
  SAVE_WORKOUT_PROGRESS_RESP: 'SAVE_WORKOUT_PROGRESS_RESP',
  UPDATE_WORKOUT_EXPIRE_STATUS: 'UPDATE_WORKOUT_EXPIRE_STATUS',
}

export default workoutKeys;